
name: ci
env:
  MARIADB_DATABASE: test_db
  MARIADB_USER: test_user
  MARIADB_PASSWORD: test_password
  MARIADB_HOST: mariadb_master
  PIP_ROOT_USER_ACTION: ignore


on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    container:
      image: mariadb:10
    services:
      mariadb-master:
        image: mariadb:lts
        env:
          MARIADB_USER: test_user
          MARIADB_PASSWORD: test_password
          MARIADB_ROOT_PASSWORD: test_password
        ports:
          - 3306/tcp
        options: >-
          --name=mariadb-master
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    env:
      PYTHONPATH : ../src/:$PYTHONPATH
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: whoami
      - run: ps ax
      - run: pwd
      - run: apt update
      - run: apt upgrade -y
      - run: apt install mariadb-client
      - run: apt install libmariadb-dev -y
      - run: apt install build-essential -y
      - run: ls /etc/apt/
      - run: cat /etc/apt/sources.list
      - run: ls /etc/apt/sources.list.d/
      - run: echo 'SHOW DATABASES;' |mariadb -h mariadb-master -u root --password=test_password 
      - run: echo 'CREATE DATABASE `panthera_test`;' |mariadb -h mariadb-master -u root --password=test_password 
      - run: echo 'SHOW DATABASES;' |mariadb -h mariadb-master -u root --password=test_password 
      - run: ls
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -e .
      - run: cd test ; python3 ../src/cli.py help
      - run: cd test ; python3 ../src/cli.py df
      - run: cd test ; python3 ../src/cli.py dc
      - run: cd test ; python3 ../src/cli.py ms

